esphome:
  name: esp32s2-switchboard
  friendly_name: esp32s2 switchboard

esp32:
  board: lolin_s2_mini
  framework:
    type: esp-idf

# Enable logging
logger:

substitutions:
  gateway: 192.168.1.1
  staticip: 192.168.1.200
  api: API
  ota: OTA

# Enable Home Assistant API
api:
  encryption:
    key: $api

ota:
  - platform: esphome
    password: $ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    gateway: $gateway
    subnet: 255.255.255.0
    static_ip: $staticip

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32S2-Switchboard"
    password: "whoopsnowifi"

captive_portal:

packages:
  sensor1: !include
    file: macrokeyboard.yaml
    vars:
      number: 1
      pin: GPIO15
  sensor2: !include
    file: macrokeyboard.yaml
    vars:
      number: 2
      pin: GPIO16
  sensor3: !include
    file: macrokeyboard.yaml
    vars:
      number: 3
      pin: GPIO17  
  sensor4: !include
    file: macrokeyboard.yaml
    vars:
      number: 4
      pin: GPIO12  
  sensor5: !include
    file: macrokeyboard.yaml
    vars:
      number: 5
      pin: GPIO33  
  sensor6: !include
    file: macrokeyboard.yaml
    vars:
      number: 6
      pin: GPIO10  
  sensor7: !include
    file: macrokeyboard.yaml
    vars:
      number: 7
      pin: GPIO11  
  sensor8: !include
    file: macrokeyboard.yaml
    vars:
      number: 8
      pin: GPIO13
